-- 1. Calculate the Total Sales generated by the Superstore.

select sum(Sales)  as  total_sales from superstore_sales;

-- 2. Calculate the Total Profit generated by the Superstore.

select sum(Profit)  as  total_profit from superstore_sales;

-- 3. Find the Total Number of Orders placed in the Superstore.

select count(distinct`Order ID`)  as   total_orders from superstore_sales;

-- 4. Find the Total Quantity of Products Sold

select sum( Quantity) as total_quantity from superstore_sales;

-- 5. Find the Total Number of Unique Customers

select count(DISTINCT `Customer ID`) as Total_Number_Customers from `superstore_sales`;

-- 6. Find the Top 10 Best-Selling Products based on Total Sales.

select `Product Name`,sum(Sales) as total_sales from superstore_sales 
group by `Product Name` order by total_sales desc limit 10;

-- 7. Find the Top 5 Most Profitable Products.

select `Product Name`,sum(Profit) as  total_profit  from superstore_sales 
group by `Product Name` order by total_profit desc LIMIT 5;

-- 8. Find the Total Sales for each Category

select Category,sum(sales) as total_sales from superstore_sales group by Category
order by total_sales desc ;

-- 9. Find the Total Profit for each Category.

select Category,sum(profit) as total_profit from superstore_sales group by Category
order by total_profit desc ;

-- 10. Find the Total Sales for each Region.

select Region,sum(sales) as total_sales from superstore_sales group by Region
order by total_sales  desc ;

-- 11. Find the Total Profit for each Region.

select Region,sum(profit) as total_profit from superstore_sales group by Region
order by total_profit desc ;

-- 12.Find the Total Sales for each Customer Segment.

select Segment,sum(sales) as total_sales from superstore_sales group by Segment
order by total_sales desc ;

-- 13. Find the Top 10 States with the Highest Sales.

select State,sum(sales) as total_sales from superstore_sales group by State
order by total_sales desc limit 10;

-- 14. Find the Average Discount for each Category.

select Category,avg(Discount) as Average_Discount from superstore_sales group by Category
order by Average_Discount desc ;

-- 15. Find the Monthly Sales Trend.

SELECT
MONTHNAME(STR_TO_DATE(`Order Date`, '%m/%d/%Y')) AS month,
SUM(Sales) AS total_sales
FROM superstore_sales
GROUP BY
MONTH(STR_TO_DATE(`Order Date`, '%m/%d/%Y')),
MONTHNAME(STR_TO_DATE(`Order Date`, '%m/%d/%Y'))
ORDER BY
MONTH(STR_TO_DATE(`Order Date`, '%m/%d/%Y'));

# 16. Find the Top 3 Products in each Category based on Total Sales.

WITH ranked_products AS
(select Category,`Product Name`,
sum(sales) as total_sales,
rank()over( PARTITION by category
order by sum(sales) desc )
as sales_rank
from `superstore_sales` group by Category,`Product Name`)
SELECT  Category,`Product Name`,total_sales,sales_rank
FROM ranked_products
WHERE sales_rank <= 3;

# 17. Find the Top 5 Customers based on Total Sales.

select `Customer Name`,sum(sales) as total_sales from superstore_sales
group by `Customer Name` order by total_sales desc  limit 5;


# 18. Find the Top 5 Customers based on Total Profit

select `Customer Name`,sum(profit) as total_profit from superstore_sales
group by `Customer Name` order by total_profit desc  limit 5;


# 19. Find the Top 3 Customers based on Total Profit.

with ranked_products AS(
select region,`Customer Name`,sum(profit) as total_profit, 
rank()over( PARTITION by Region
order by sum(profit) desc )
as sales_rank
from superstore_sales
GROUP BY Region, `Customer Name`)
SELECT *
FROM ranked_products
WHERE sales_rank <= 3;



# 20. Find the Top 2 Products in each Category based on Total Profit.


WITH ranked_products AS (
SELECT
Category`Product Name`,
SUM(Profit) AS total_profit,
RANK() OVER (
PARTITION BY Category
ORDER BY SUM(Profit) DESC) AS sales_rank
FROM superstore_sales
GROUP BY Category, `Product Name`)
SELECT *
FROM ranked_products
WHERE sales_rank <= 2;


